version: '3.8'
services:

  db:
    image: postgres:16.1
    platform: linux/x86_64
    container_name: postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf' # 追加
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      # - POSTGRES_INITDB_ARGS=initdbコマンドを実行するときに渡すパラメータを指定
      # - POSTGRES_INITDB_WALDIR or POSTGRES_INITDB_WALDIR=ログの出力パスを指定
      # - POSTGRES_HOST_AUTH_METHOD=認証方法
      # - PGDATA=DBファイルのパス
    ports:
      - 5431:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d # この行を追加しただけ
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf # 追加
      - ./src/postgres:/home
    working_dir: /home
volumes:
  db-store: